
import type { Team, Match } from './types';

export const TEAMS: Team[] = [
  {
    id: 1,
    name: "Swarajya Cricket Club",
    logoColor: "bg-orange-500",
    players: [
      { id: 101, name: "Rahul Chavan (C)", role: 'Batsman' },
      { id: 102, name: "Sachin Vichare", role: 'Batsman' },
      { id: 103, name: "Siddhesh Nakti", role: 'Batsman' },
      { id: 104, name: "Jaydip Patil", role: 'All-Rounder' },
      { id: 105, name: "Kunal Kamble", role: 'All-Rounder' },
      { id: 106, name: "Pranal Nakti", role: 'All-Rounder' },
      { id: 107, name: "Siddhesh Kamble", role: 'All-Rounder' },
      { id: 108, name: "Raju Nakti (VC)", role: 'Bowler' },
      { id: 109, name: "Pravin Nakti", role: 'Bowler' },
      { id: 110, name: "Prasad Nakti", role: 'Bowler' },
      { id: 111, name: "Mahesh Mohite", role: 'Bowler' },
      { id: 112, name: "Sagar Vichare (Stand by)", role: 'All-Rounder' },
      { id: 113, name: "Sagar Kamble (Stand by)", role: 'All-Rounder' },
      { id: 114, name: "Sajan Bhayde (Stand by)", role: 'All-Rounder' },
      { id: 115, name: "Pratham Nakti (Stand by)", role: 'All-Rounder' },
    ],
  },
  {
    id: 2,
    name: "Rising Stars Shiste",
    logoColor: "bg-purple-500",
    players: [
      { id: 201, name: "Prakash Kamble (Team Owner)", role: "All-Rounder" },
      { id: 202, name: "Dashrath Dhumal (Team Manager)", role: "All-Rounder" },
      { id: 203, name: "Sujet Chalke (C)", role: "All-Rounder" },
      { id: 204, name: "Raj Patil (VC)", role: "All-Rounder" },
      { id: 205, name: "Sanjay Kamble", role: "All-Rounder" },
      { id: 206, name: "Akshay Chalke", role: "All-Rounder" },
      { id: 207, name: "Darshan Kamble", role: "All-Rounder" },
      { id: 208, name: "Ajay Mohite", role: "All-Rounder" },
      { id: 209, name: "Harsh Chalke", role: "All-Rounder" },
      { id: 210, name: "Shravan Kamble", role: "All-Rounder" },
      { id: 211, name: "Nandan Nakti", role: "All-Rounder" },
      { id: 212, name: "Ajay Bhayde", role: "All-Rounder" },
      { id: 213, name: "Sachin Mohite", role: "All-Rounder" },
      { id: 214, name: "Vaibhav Patil", role: "All-Rounder" },
      { id: 215, name: "Jaydip Chalke", role: "All-Rounder" },
      { id: 216, name: "Pranamya Patil", role: "All-Rounder" },
      { id: 217, name: "Aayush Gharat", role: "All-Rounder" },
      { id: 218, name: "Sujal Mohite", role: "All-Rounder" },
      { id: 219, name: "Rushi Gharat", role: "All-Rounder" },
      { id: 220, name: "Samir Kamble", role: "All-Rounder" },
    ],
  },
  {
    id: 3,
    name: "Dongri Jakhamata",
    logoColor: "bg-green-500",
    players: [
      { id: 301, name: 'Prathamesh Bhayde (C)', role: 'All-Rounder' },
      { id: 302, name: 'Jay Nakti (VC)', role: 'All-Rounder' },
      { id: 303, name: 'Yogesh Kamble', role: 'Batsman' },
      { id: 304, name: 'Mayur Sishatkar', role: 'Batsman' },
      { id: 305, name: 'Prasad Patil', role: 'Batsman' },
      { id: 306, name: 'Pratap Nakti', role: 'All-Rounder' },
      { id: 307, name: 'Pranal Bhayde', role: 'Bowler' },
      { id: 308, name: 'Darshan Nakti', role: 'Bowler' },
      { id: 309, name: 'Deepak Nakti', role: 'Bowler' },
      { id: 310, name: 'Ajay Baikar', role: 'Batsman' },
      { id: 311, name: 'Aakash Nakti', role: 'Batsman' },
      { id: 312, name: 'Manish Nakti', role: 'All-Rounder' },
      { id: 313, name: 'Hastak Bhayde', role: 'Bowler' },
      { id: 314, name: 'Mahesh Patil', role: 'All-Rounder' },
      { id: 315, name: 'Tej Nakti', role: 'Batsman' },
    ],
  },
  {
    id: 4,
    name: "Royal Aagri",
    logoColor: "bg-blue-500",
    players: [
        { id: 401, name: 'Vivek Patil (C)', role: 'Batsman' },
        { id: 402, name: 'Sushant Nakti (VC)', role: 'Batsman' },
        { id: 403, name: 'Uddesh Nakti', role: 'All-Rounder' },
        { id: 404, name: 'Sahil Patil', role: 'Batsman' },
        { id: 405, name: 'Ganesh Gharat', role: 'All-Rounder' },
        { id: 406, name: 'Sushil Nakti', role: 'Bowler' },
        { id: 407, name: 'Ajinkya Bhayde', role: 'Batsman' },
        { id: 408, name: 'Omkar Mohite (WK)', role: 'Wicket-Keeper' },
        { id: 409, name: 'Vivek Bhayde', role: 'Batsman' },
        { id: 410, name: 'Akash Mohite (WK)', role: 'Wicket-Keeper' },
        { id: 411, name: 'Vishal Bhayde', role: 'Bowler' },
        { id: 412, name: 'Sajan Patil', role: 'All-Rounder' },
        { id: 413, name: 'Prasad Mohite', role: 'Batsman' },
        { id: 414, name: 'Shubham Nakti', role: 'Bowler' },
        { id: 415, name: 'Prashant Mohite', role: 'Bowler' },
    ],
  },
    {
    id: 5,
    name: "UK Warriors",
    logoColor: "bg-indigo-500",
    players: [
      { id: 501, name: "Jaydeep Chalke (C)", role: "All-Rounder" },
      { id: 502, name: "Prafull Bhayde (VC)", role: "All-Rounder" },
      { id: 503, name: "Avinash Chalke", role: "All-Rounder" },
      { id: 504, name: "Kumar Gharat", role: "All-Rounder" },
      { id: 505, name: "Sarthak Patil", role: "All-Rounder" },
      { id: 506, name: "Siddesh Mohite", role: "All-Rounder" },
      { id: 507, name: "Ninad Patil", role: "All-Rounder" },
      { id: 508, name: "Haresh Mohite", role: "All-Rounder" },
      { id: 509, name: "Karan Kamble", role: "All-Rounder" },
      { id: 510, name: "Vaibhav Nakti", role: "All-Rounder" },
      { id: 511, name: "Bharat Kamble", role: "All-Rounder" },
      { id: 512, name: "Sahil J. Patil", role: "All-Rounder" },
      { id: 513, name: "Sahil .S. Patil", role: "All-Rounder" },
      { id: 514, name: "Krunal Gharat", role: "All-Rounder" },
      { id: 515, name: "Naush Patil", role: "All-Rounder" },
      { id: 516, name: "Raj Kamble", role: "All-Rounder" },
      { id: 517, name: "Vikas Patil (Coach)", role: "All-Rounder" },
      { id: 518, name: "Rahul Patil (Coach)", role: "All-Rounder" },
      { id: 519, name: "Dipesh Gharat (Coach)", role: "All-Rounder" },
    ],
  },
  {
    id: 6,
    name: "Game Changer Sports Club",
    logoColor: "bg-yellow-500",
    players: [
      { id: 601, name: "Raj Nakti (C)", role: "Batsman" },
      { id: 602, name: "Pramod Nakti", role: "All-Rounder" },
      { id: 603, name: "Dipesh Nakti", role: "All-Rounder" },
      { id: 604, name: "Prakash Nakti", role: "All-Rounder" },
      { id: 605, name: "Rohit Nakti", role: "All-Rounder" },
      { id: 606, name: "Bharat Patil", role: "All-Rounder" },
      { id: 607, name: "Ajinkya Patil", role: "All-Rounder" },
      { id: 608, name: "Tushar Chalke", role: "All-Rounder" },
      { id: 609, name: "Devesh Nakti", role: "All-Rounder" },
      { id: 610, name: "Aniket Chalke", role: "All-Rounder" },
      { id: 611, name: "Raj Kamble", role: "All-Rounder" },
      { id: 612, name: "Sudarshan Chalke", role: "All-Rounder" },
      { id: 613, name: "Hardik Mohite", role: "All-Rounder" },
      { id: 614, name: "Ved Patil", role: "All-Rounder" },
      { id: 615, name: "Athrav Biradi", role: "All-Rounder" },
      { id: 616, name: "Santosh Patil", role: "All-Rounder" },
      { id: 617, name: "Vishal Chalke", role: "All-Rounder" },
    ],
  },
];

export const MATCH_SCHEDULE: Match[] = [
  // Day 1: 3rd September 2025
  { id: 1, team1Id: 1, team2Id: 2, date: "2025-09-03 11:00", venue: "Wakde Mall, Shiste" },
  { id: 2, team1Id: 3, team2Id: 4, date: "2025-09-03 11:30", venue: "Wakde Mall, Shiste" },
  { id: 3, team1Id: 5, team2Id: 6, date: "2025-09-03 12:00", venue: "Wakde Mall, Shiste" },
  { id: 4, team1Id: 1, team2Id: 3, date: "2025-09-03 12:30", venue: "Wakde Mall, Shiste" },
  { id: 5, team1Id: 4, team2Id: 6, date: "2025-09-03 13:00", venue: "Wakde Mall, Shiste" },
  { id: 6, team1Id: 5, team2Id: 2, date: "2025-09-03 13:30", venue: "Wakde Mall, Shiste" },
  { id: 7, team1Id: 3, team2Id: 6, date: "2025-09-03 14:00", venue: "Wakde Mall, Shiste" },
  
  // Day 2: 4th September 2025
  { id: 8, team1Id: 1, team2Id: 5, date: "2025-09-04 11:00", venue: "Wakde Mall, Shiste" },
  { id: 9, team1Id: 4, team2Id: 2, date: "2025-09-04 11:30", venue: "Wakde Mall, Shiste" },
  { id: 10, team1Id: 6, team2Id: 1, date: "2025-09-04 12:00", venue: "Wakde Mall, Shiste" },
  { id: 11, team1Id: 5, team2Id: 4, date: "2025-09-04 12:30", venue: "Wakde Mall, Shiste" },
  { id: 12, team1Id: 2, team2Id: 3, date: "2025-09-04 13:00", venue: "Wakde Mall, Shiste" },
  { id: 13, team1Id: 1, team2Id: 4, date: "2025-09-04 13:30", venue: "Wakde Mall, Shiste" },
  { id: 14, team1Id: 2, team2Id: 6, date: "2025-09-04 14:00", venue: "Wakde Mall, Shiste" },
  { id: 15, team1Id: 3, team2Id: 5, date: "2025-09-04 14:30", venue: "Wakde Mall, Shiste" },
];
